### ISSUE TITLE
Accessibility: skip navigation

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oet-theme#1]
Testing of the theme revealed that we're not providing a way for people navigating with a keyboard to easily skip to the content of the site. Their recommendation:

 > Provide a method for skipping past repetitive navigation links at the beginning of the page that points to a target at the beginning of the main content area of the page.   There are several methods that can successfully achieve this requirement, which are outlined at http://www.webaim.org/techniques/skipnav/#creating

I believe the twentytwelve theme (which this is based on) had a way to do it, but it's not enabled here. Please enable it for this theme and test accordingly. Thanks

**Comment by johnpaulbalagolan** [comment]
Added skip navigation and tested this.

fixed #1.
