### ISSUE TITLE
OII - slider option on home

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oet-theme#10]
They may want to use a slider on the home where the image at the top is now (http://oii-test.navnorth.com). The [Slideshow plugin](https://wordpress.org/plugins/slideshow-jquery-image-gallery/) we used on MBK and OET is already approved and ready to use. I think they'd like a style similar to MBK but with text position below the image like the current caption style is. And of course it needs to be responsive, similar to how the main image on the front is now.

Please load the plugin on your dev environment and create a test page based on content from the test server home, but using a slideshow in place of that top image. Create a custom style for the slideshow, in the general settings for the plugin. When you're satisfied with how it looks, copy it to a *new* page on the test server, called Home w/ Slider, so the client can look at both options.

Here's the slideshow style from http://mbk.ed.gov for reference: https://gist.github.com/joehobson/a843913cfe43f9b093a6

**Comment by joehobson** [comment]
@johnpaulbalagolan : What's the status on this task? I would like to show the client a slider home option on the test server at my meeting with them tomorrow. Thanks

**Comment by johnpaulbalagolan** [comment]
I am working on this sir. Will have it ready before your meeting tomorrow.

Thanks.

**Comment by johnpaulbalagolan** [comment]
@joehobson there seems to be a bug on the customize settings for the slideshow when creating a customize stylesheet. My styles weren't save for some reason both in oii-test.navnorth.com and my development machine.

**Comment by johnpaulbalagolan** [comment]
@joehobson I committed the responsive view of the slideshow and did the edit in mainstyles.css as I couldn't save custom styles in Slideshows > General Settings  > Custom Styles.
