### ISSUE TITLE
test latest Simple Share Buttons plugin update

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oet-theme#14]
the Simple Share Buttons Adder plugin (https://wordpress.org/plugins/simple-share-buttons-adder/) has been updated to v6.02 and includes some XSS fixes. Test the OET theme and Stories plugin with this update (on WP MultiSite) to make sure it won't cause us any issues when the production server is updated. 

While you're at it, see if you can find a solution for this GAT request: https://trello.com/c/mYNYPAc5/15-sharing-links-only-use-the-assessment-url-drop-the-parameters

**Comment by johnpaulbalagolan** [comment]
With regards to the GAT request, this can be done but I might need to modify that plugin itself. I'll try if I can use filter through theme or the GAT plugin so that it will not include the query string parameters.

Thanks.

**Comment by johnpaulbalagolan** [comment]
I've tested the latest version of Simple Share Buttons Adder on both MU and stand-alone WordPress installation together with WP OET Theme and WP Stories Plugin. I didn't encounter any issues.

Fyi. Thanks.

**Comment by johnpaulbalagolan** [comment]
done #14

**Comment by johnpaulbalagolan** [comment]
Sir, as per checking I can't override the url using filter inside the theme or another plugin. So I will have to use javascript to override the url since editing the plugin itself will become an issue later one when there's new version of the plugin.

**Comment by johnpaulbalagolan** [comment]
I committed the code to override the url when using Simple Sharing Buttons on WP-Gap Analysis plugin.
