### ISSUE TITLE
OII Program templates - main and child

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oet-theme#15]
Create a second template for program sub pages (example: http://oii-test.navnorth.com/what-we-do/innovation/investing-in-innovation-i3/awards/). Name it "Program Sub-page template"

Rename the other template to "Program Main template" (example: http://oii-test.navnorth.com/what-we-do/innovation/investing-in-innovation-i3/)

**Comment by johnpaulbalagolan** [comment]
created second template for program sub pages and updated the Program template to Program Main Template. done #15
