### ISSUE TITLE
OII Program Main page contact box

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oet-theme#17]
We need to have a contact box on most of the Program main pages, like the one we mocked up on the [i3 page](http://oii-test.navnorth.com/what-we-do/innovation/investing-in-innovation-i3/). It seems like the best way to do this and fit the style of the mockup that they liked is to add a metabox for the Program Main template for Contact Info. It will need to be WYSIWYG so they can modify links and styles a little as necessary. And then if the contact info is left empty, don't show the box at all.

Do you think this would work? If so, implement it.

**Comment by johnpaulbalagolan** [comment]
Hi Sir,

I think that would work. I¹ll implement this after implementing the fixes on
OII ECI Content Exporter plugin.

Thanks.

From:  joe hobson <notifications@github.com>
Reply-To:  navnorth/wp-oet-theme
<reply+00af40eaa8328ec2451d585da5d7253c28760c71d347221d92cf0000000111a4203f9
2a169ce056d7b55@reply.github.com>
Date:  Thu, 25 Jun 2015 13:02:07 -0700
To:  navnorth/wp-oet-theme <wp-oet-theme@noreply.github.com>
Cc:  John Paul Balagolan <johnpaulbalagolan@gmail.com>
Subject:  [wp-oet-theme] OII Program Main page contact box (#17)


We need to have a contact box on most of the Program main pages, like the
one we mocked up on the i3 page
<http://oii-test.navnorth.com/what-we-do/innovation/investing-in-innovation-
i3/> . It seems like the best way to do this and fit the style of the mockup
that they liked is to add a metabox for the Program Main template for
Contact Info. It will need to be WYSIWYG so they can modify links and styles
a little as necessary. And then if the contact info is left empty, don't
show the box at all.

Do you think this would work? If so, implement it.


Reply to this email directly or view it on GitHub
<https://github.com/navnorth/wp-oet-theme/issues/17> .
