### ISSUE TITLE
OII Related Posts widget - exclude current page

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oet-theme#18]
I've noticed that the Related Posts widget shows a link to the current page, which obviously is unnecessary. Example: http://oii-test.navnorth.com/what-we-do/arts/arts-in-education-model-development-and-dissemination-grants-program/

Original intent was to have it just show recent news articles, so maybe rather than trying to exclude the current page, just have it only show posts (not pages)

**Comment by johnpaulbalagolan** [comment]
hi sir, I updated the related posts widget to exclude the current page for now as somehow WP_Query is returning everything even if post_type is set to only "post" in the arguments. It returns everything regardless of post type in a category.

I am still working on the workaround on this.

**Comment by johnpaulbalagolan** [comment]
fixed #18 with the latest source I committed by using filter
