### ISSUE TITLE
Skip to Content

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oet-theme#19]
When you're viewing content and using keyboard tabs to navigate, hitting enter on the "Skip to Content" link skips to the content, but doesn't change the focus, so the next time you tab it goes back to the header. So there's no real way to skip tabbing through all of the links in the header.

**Comment by johnpaulbalagolan** [comment]
fixed #19 on the latest version of wp-oii-theme source committed in github.

**Comment by joehobson** [comment]
reopening this one so you can implement the same on the OET theme templates since it seems to have the same issue.

**Comment by johnpaulbalagolan** [comment]
I have implemented the fix to Skip To Content in OET Theme
