### ISSUE TITLE
Google Analytics after removing Yoast

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oet-theme#21]
We had to remove the Yoast Google Analytics plugin on OET for the GAT, since the way Yoast was setup didn't really give us access to setting userid. But we had/have some functions in the OET theme that were set to use the Yoast version of the GA functions for events. You can see the changes I made with this commit: https://github.com/navnorth/wp-oet-theme/commit/a2bce5321134ed53352fbc7f942d1dc8853980d2

Just not sure I got them all or that the changes are tracking correctly. I added you to the OET Test GA account so you can look at the data our staging server is reporting. Go through parts of our staging site and make sure we're tracking okay. They like to see data on how many people download publications so look at that specifically, and then see if there are any other templates where we need to switch from the Yoast functions.

**Comment by joehobson** [comment]
Here's are 2 examples of pages with download links. Looks like they're using something like ```onmousedown="_sendEvent('Downloads','pdf',...```

 * http://oet-test.navnorth.com/futureready/infrastructure/
 * http://oet-test.navnorth.com/futureready/professional-learning/step-1-determine-district-readiness/

**Comment by johnpaulbalagolan** [comment]
fixed #21
