### ISSUE TITLE
check latest XSS hack - remove_query_arg()

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oet-theme#4]
A new WP XSS vulnerability was announced this week and it is possible that our themes and plugins have issues. 

Announcement: https://blog.sucuri.net/2015/04/security-advisory-xss-vulnerability-affecting-multiple-wordpress-plugins.html

Write up of the issue (esp last paragraph): https://yoast.com/coordinated-security-release/

WP tips on usage: https://make.wordpress.org/plugins/2015/04/20/fixing-add_query_arg-and-remove_query_arg-usage/

Task for you: please check the OET theme for the vulnerability, see if we need to make any changes. There is a custom filter in place in functions.php which we implemented in December. You can read the reasoning and find links to articles on this doc: https://docs.google.com/a/adlnet.gov/document/d/1T6k3II_qp11xMYhOxk0-gg0FQeHFv-6DgWP9AlLCRHM/edit?usp=sharing

We will likely need to check and make updates to other themes and plugins so learn what you can about it now. Thanks

**Comment by johnpaulbalagolan** [comment]
fixed #4

**Comment by joehobson** [comment]
Did you have to spend much time testing the fix on the theme? We will need to go through other themes and plugins to check and test for this fix so I need to know how much time to set aside for it.

**Comment by johnpaulbalagolan** [comment]
For this specify vulnerability, fixing it will probably take 5-15 mins depending on the number of occurrence of the vulnerable code. Testing it will vary depending on how the code is used inside the plugin or theme. So we need to trace how it's used. I would probably suggest setting aside 1-2 hrs for testing the fix. This includes identifying how it's used.

Thanks.
