### ISSUE TITLE
OII - smaller, dimmer external link image

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oet-theme#7]
The external link image (external_link.png) is a little too large and a little too bright when it's used many times on a page ([example](http://oii-test.navnorth.com/arts-education/update-on-oiis-fy-2015-grant-competitions/)). Resize the image to 13x13 pixels but make sure it's still clear and not pixelated. There is an svg in the same folder if that helps in transforming it. For the basic style, try making the opacity 80% and then full opacity when you mouseover the image... if that's possible. Don't spend too much time on it, but see if you can make something like that work.
Thanks

**Comment by johnpaulbalagolan** [comment]
done implementing the adjustment. fixed #7
