### ISSUE TITLE
OII - header social options

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oet-theme#9]
The header bar displays links to social media pages - Facebook, Twitter, LinkedIn, etc. Options are set in the theme's Social Media Options page. Only problem is that there's no logic to when to display the links or not. please update the header.php to display icons for any of the social media options where a URL has been entered in the theme settings, but don't display ones where it's empty or Null.

OII will probably only use Twitter and Newsletter at launch, but may want to add others later

**Comment by johnpaulbalagolan** [comment]
fixed #9
